#################
### WALLPAPER ###
#################
wallpaper {
    monitor = DP-1
    path = /home/robott/Pictures/wallpapers/wallhaven-7peg59.png
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/robott/Pictures/wallpapers/wallhaven-7peg59.png
}
